name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  migrate:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      URL_DATABASE_ENV: ${{ secrets.URL_DATABASE_ENV }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: RUN <MIGRATE>
        run: go run migrate/migrate.go

  deploy:
    runs-on: ubuntu-latest
    needs: [build, migrate]
    env:
      URL_DEPLOY: ${{ secrets.URL_DEPLOY }}
    steps:
      - uses: actions/checkout@v3
      - name: WEB
        run: curl -X POST $URL_DEPLOY
